FROM python:3.10-alpine
ADD server1.py .
ADD requirements.txt .
RUN pip install -r requirements.txt
RUN mkdir ./templates
ADD ./templates/index.html ./templates
ADD ./templates/index2.html ./templates
CMD ["python", "./server1.py"]